site_name: YuZhong Chen
site_description: Personal website of YuZhong Chen
site_url: https://yuzhong-chen.github.io
repo_url: https://github.com/YuZhong-Chen/yuzhong-chen.github.io
repo_name: YuZhong-Chen/yuzhong-chen.github.io

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
